development:
  host:  127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: portable_development
  pool: 5
  username: portable
  password: portable

test:
  host:  127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: portable_test
  pool: 5
  username: portable
  password: portable

production:
  adapter: mysql2
  encoding: utf8
  database: portable_production
  pool: 5
  username: portable
  password: something_secret
